***NUMPY INTRODUCYION:***


In [11]:
#CREATE ARRAY:
import numpy as np
a = np.arange(7)
print(a)
a.shape

[0 1 2 3 4 5 6]


(7,)

In [12]:
a2 = a[np.newaxis, :]
print(a2)
a2.shape

[[0 1 2 3 4 5 6]]


(1, 7)

In [13]:
a2 = a[: ,np.newaxis]
print(a2)
a2.shape

[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]]


(7, 1)

In [15]:
a3= a2[: ,np.newaxis]
print(a3)
a3.shape

[[[0]]

 [[1]]

 [[2]]

 [[3]]

 [[4]]

 [[5]]

 [[6]]]


(7, 1, 1)

***CREATE ARRAYS WITH NUMPY:***

In [47]:
a = np.array([1,2,3,4,5,6])
b = np.array([(1,2,3,4,5,6),(5,6,7,8,8,8)])

In [18]:
print(a)

[1 2 3 4 5 6 7 8]


In [19]:
print(b)

[[1 2 3 4 5 6]
 [5 6 7 8 8 8]]


In [20]:
a.shape

(8,)

In [21]:
b.shape

(2, 6)

In [25]:
b2 = b[: ,np.newaxis]
print(b2)
b2.shape

[[[1 2 3 4 5 6]]

 [[5 6 7 8 8 8]]]


(2, 1, 6)

***initialize the arrays:***

In [ ]:
zeros = np.zeros((7,5)) #(rows, columns)
zeros

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [41]:
zeros = np.ones(((7,5))) #(rows, columns)
zeros

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
#initialize the arrays in user:
full = np.full((2, 6),3)
full

array([[3, 3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3, 3]])

In [32]:
full.dtype

dtype('int64')

In [33]:
type(full)

numpy.ndarray

In [34]:
a.size

8

In [38]:
len(b)

2

In [39]:
a.ndim

1

In [43]:
full.ndim

2

In [ ]:
a 

array([1, 2, 3, 4, 5, 6, 7, 8])

In [46]:
b

array([[1, 2, 3, 4, 5, 6],
       [5, 6, 7, 8, 8, 8]])

***operation in arrays:***

In [48]:
c = a-b
c

array([[ 0,  0,  0,  0,  0,  0],
       [-4, -4, -4, -4, -3, -2]])

In [ ]:
c = a+b
c

array([[ 2,  4,  6,  8, 10, 12],
       [ 6,  8, 10, 12, 13, 14]])

In [50]:
c = a*b
c

array([[ 1,  4,  9, 16, 25, 36],
       [ 5, 12, 21, 32, 40, 48]])

In [51]:
c = a/b
c

array([[1.        , 1.        , 1.        , 1.        , 1.        ,
        1.        ],
       [0.2       , 0.33333333, 0.42857143, 0.5       , 0.625     ,
        0.75      ]])

In [ ]:
a

array([1, 2, 3, 4, 5, 6])

In [53]:
a**2

array([ 1,  4,  9, 16, 25, 36])

In [56]:
a**4


array([   1,   16,   81,  256,  625, 1296])