***NUMPY (PART-2) :***

In [18]:
import numpy as np
import pandas as pd

In [19]:
empty  = np.empty((2,3))
print(empty)
print("-----------")
print(empty[1])

[[6.23042070e-307 4.67296746e-307 1.69121096e-306]
 [3.22647253e-307 2.67018777e-306 1.46205510e-311]]
-----------
[3.22647253e-307 2.67018777e-306 1.46205510e-311]


In [20]:
empty  = np.empty((2,4))
print(empty)
print("-----------")
print(empty[1])

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]
-----------
[0. 0. 0. 0.]


In [21]:
x = np.arange(6)
x

array([0, 1, 2, 3, 4, 5])

In [22]:
#array of even numbers from 0 to 23;
even = np.arange(0,23,2) #(starting,ending,addition)
print(even)

[ 0  2  4  6  8 10 12 14 16 18 20 22]


In [23]:
#array of odd numbers from 0 to 23;
odd = np.arange(1,23,2) #(starting,ending,addition)
print(odd)

[ 1  3  5  7  9 11 13 15 17 19 21]


In [24]:
lin = np.linspace(0, 20,num=10)
lin

array([ 0.        ,  2.22222222,  4.44444444,  6.66666667,  8.88888889,
       11.11111111, 13.33333333, 15.55555556, 17.77777778, 20.        ])

In [25]:
lin.dtype

dtype('float64')

In [26]:
arr = np.arange(7)
arr

array([0, 1, 2, 3, 4, 5, 6])

In [27]:
arr = np.array([2,4,5,1,6,3,9,8])
arr

array([2, 4, 5, 1, 6, 3, 9, 8])

In [28]:
#sort the array:
arr = np.sort(arr)
arr

array([1, 2, 3, 4, 5, 6, 8, 9])

In [29]:
arr.shape      

(8,)

In [30]:
a = np.array([1,2,3,4,5,6,7])

In [31]:
a[1] #indexing

np.int64(2)

In [33]:
a = np.arange(40)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39])

In [38]:
a.max(axis=0)

np.int64(39)

In [35]:
a.min()

np.int64(0)

In [43]:
a = np.arange(0,100,2).reshape(5,10)
a

array([[ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28, 30, 32, 34, 36, 38],
       [40, 42, 44, 46, 48, 50, 52, 54, 56, 58],
       [60, 62, 64, 66, 68, 70, 72, 74, 76, 78],
       [80, 82, 84, 86, 88, 90, 92, 94, 96, 98]])

In [44]:
a.min()

np.int64(0)

In [45]:
a.max(axis=0)

array([80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [46]:
a.min(axis=1)

array([ 0, 20, 40, 60, 80])