***NUMPY (PART-2) :***

In [2]:
import numpy as np
import pandas as pd

In [3]:
empty  = np.empty((2,3))
print(empty)
print("-----------")
print(empty[1])

[[6.23042070e-307 4.67296746e-307 1.69121096e-306]
 [3.22647253e-307 2.67018777e-306 1.05699581e-307]]
-----------
[3.22647253e-307 2.67018777e-306 1.05699581e-307]


In [4]:
empty  = np.empty((2,4))
print(empty)
print("-----------")
print(empty[1])

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]
-----------
[0. 0. 0. 0.]


In [5]:
x = np.arange(6)
x

array([0, 1, 2, 3, 4, 5])

In [6]:
#array of even numbers from 0 to 23;
even = np.arange(0,23,2) #(starting,ending,addition)
print(even)

[ 0  2  4  6  8 10 12 14 16 18 20 22]


In [7]:
#array of odd numbers from 0 to 23;
odd = np.arange(1,23,2) #(starting,ending,addition)
print(odd)

[ 1  3  5  7  9 11 13 15 17 19 21]


In [8]:
lin = np.linspace(0, 20,num=10)
lin

array([ 0.        ,  2.22222222,  4.44444444,  6.66666667,  8.88888889,
       11.11111111, 13.33333333, 15.55555556, 17.77777778, 20.        ])

In [9]:
lin.dtype

dtype('float64')

In [10]:
arr = np.arange(7)
arr

array([0, 1, 2, 3, 4, 5, 6])

In [11]:
arr = np.array([2,4,5,1,6,3,9,8])
arr

array([2, 4, 5, 1, 6, 3, 9, 8])

In [14]:
#sort the array:
arr = np.sort(arr)
arr

array([1, 2, 3, 4, 5, 6, 8, 9])