# Naive Bayes Algorithm:

In [4]:
# import libraries:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB, MultinomialNB, BernoulliNB
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

In [5]:
# load the iris dataset:
from sklearn.datasets import load_iris
iris = load_iris()

# split the dataset into features and target variable:
X = iris.data
y = iris.target

# split the dataset into training and testing sets:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)



In [7]:
# model initialization:
model = GaussianNB()

# train the model:
model.fit(X_train, y_train)

# predict the target variable for the test set:
y_pred = model.predict(X_test)

# evaluate the model:

print("Accuracy_score:", accuracy_score(y_test, y_pred))
print("Confusion_matrix:\n", confusion_matrix(y_test, y_pred))
print("Classification_report:\n", classification_report(y_test, y_pred))



Accuracy_score: 1.0
Confusion_matrix:
 [[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]
Classification_report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      1.00      1.00         9
           2       1.00      1.00      1.00        11

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30



---

In [8]:
# model initialization:
model = MultinomialNB()

# train the model:
model.fit(X_train, y_train)

# predict the target variable for the test set:
y_pred = model.predict(X_test)

# evaluate the model:
print("Accuracy_score:", accuracy_score(y_test, y_pred))
print("Confusion_matrix:\n", confusion_matrix(y_test, y_pred))
print("Classification_report:\n", classification_report(y_test, y_pred))

Accuracy_score: 0.9
Confusion_matrix:
 [[10  0  0]
 [ 0  9  0]
 [ 0  3  8]]
Classification_report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       0.75      1.00      0.86         9
           2       1.00      0.73      0.84        11

    accuracy                           0.90        30
   macro avg       0.92      0.91      0.90        30
weighted avg       0.93      0.90      0.90        30



---

In [9]:
# model initialization:
model = BernoulliNB()

# train the model:
model.fit(X_train, y_train)

# predict the target variable for the test set:
y_pred = model.predict(X_test)

# evaluate the model:
print("Accuracy_score:", accuracy_score(y_test, y_pred))
print("Confusion_matrix:\n", confusion_matrix(y_test, y_pred))
print("Classification_report:\n", classification_report(y_test, y_pred))

Accuracy_score: 0.3
Confusion_matrix:
 [[ 0 10  0]
 [ 0  9  0]
 [ 0 11  0]]
Classification_report:
               precision    recall  f1-score   support

           0       0.00      0.00      0.00        10
           1       0.30      1.00      0.46         9
           2       0.00      0.00      0.00        11

    accuracy                           0.30        30
   macro avg       0.10      0.33      0.15        30
weighted avg       0.09      0.30      0.14        30



c:\ProgramData\miniconda3\envs\ml_eda\lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\ProgramData\miniconda3\envs\ml_eda\lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\ProgramData\miniconda3\envs\ml_eda\lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result